[package]
name = "quantum_resistant_blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
pqcrypto-ntru = "*"
pqcrypto-falcon = "*"
solana-sdk = "*"
serde = { version = "1.0", features = ["derive"] }
bincode = "*"
tokio = { version = "1", features = ["full"] }

